services:
  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBIT_ERLANG_COOKIE: "EUAMOAJENNIFER"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
     - "15672:15672"
     - "5672:5672"