services:
  sqlserver:
    build: .
    ports:
      - "1433:1433"

  rabbit:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    hostname: localhost
    environment:
      RABBIT_ERLANG_COOKIE: "arroz"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
     - "15672:15672"
     - "5672:5672"